# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            UGCNormal
tagline:          'Um normalizador textual para o português brasileiro'
description:      'Um normalizador textual de conteúdo gerado por usuário para o português brasileiro.'
url:              tfcbertaglia.github.io/ugcnormal
baseurl:          /ugcnormal

author:
  name:           'Thales Bertaglia'
  url:            tfcbertaglia.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           github.com/tfcbertaglia
