# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            UGCNormal
tagline:          'Um normalizador textual para o português brasileiro'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              tfcbertaglia.github.io/ugnormal
baseurl:          /ugcnormal/

author:
  name:           'Thales Bertaglia'
  url:            tfcbertaglia.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           github.com/tfcbertaglia
